name: Rocksteady
favicon: null
layout_spectrum: 1
typography_spectrum: 0.66027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b021f'
    - '#fff1ee'
    - '#5e1567'
    - '#bdb1c4'
    - '#a73a8b'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
